### ISSUE TITLE
i have issue, 

### ISSUE THREAD

**Issue by ayoubidg** [behnambm/nordvpn-checker#1]
i have issue, 
this is the error 

Traceback (most recent call last):
  File "nord-checker.py", line 29, in <module>
    subprocess.check_output(['nordvpn','logout'])
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['nordvpn', 'logout']' returned non-zero exit status 1.
root@instance-1:/home/Discord/nordvpn-checker# subprocess.CalledProcessError: Command '['nordvpn', 'logout']' returned non-zero exit status 1.

**Comment by behnambm** [comment]
problem fixed :)
