### ISSUE TITLE
too many value 

### ISSUE THREAD

**Issue by 7979sahil** [behnambm/nordvpn-checker#10]
when I am running the script its throwing this error 
Traceback (most recent call last):
  File "/home/kali/nordvpn-checker/nord-checker.py", line 138, in <module>
    read_file(args)
  File "/home/kali/nordvpn-checker/nord-checker.py", line 93, in read_file
    email, password = line.strip().split(':')
ValueError: too many values to unpack (expected 2)

**Comment by behnambm** [comment]
This is because you've got more than one colon.
The correct format is `email:password`
