### ISSUE TITLE
Command '['nordvpn', 'c', 'united_states']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by shana055** [behnambm/nordvpn-checker#16]
I am getting this error when trying to connect to NordVPN , Linux:

**subprocess.CalledProcessError: Command '['nordvpn', 'c', 'united_states']' returned non-zero exit status 1.**

Traceback (most recent call last):
File "/usr/lib64/python3.7/subprocess.py", line 411, in check_output
**kwargs).stdout
 File "/usr/lib64/python3.7/subprocess.py", line 512, in run
output=stdout, stderr=stderr)

**Comment by behnambm** [comment]
what command do you use?

**Comment by shana055** [comment]
I am using : 'nordvpn c united states'

‫בתאריך יום ה׳, 28 באפר׳ 2022 ב-13:39 מאת ‪Behnam Mohammadzadeh‬‏ <‪
***@***.***‬‏>:‬

**Comment by shana055** [comment]
sorry, I did spell it right, it's this command : nordvpn c united_states

I connect and terminate (with command : nordvpn d) several times
successfully , and for some reason it fails to connect at some point..


Thanks

‫בתאריך יום ה׳, 28 באפר׳ 2022 ב-13:56 מאת ‪Shoshana Soloveichik‬‏ <‪
***@***.***‬‏>:‬

**Comment by behnambm** [comment]
you're using official `nordvpn` package not my `nordvpn-checker` script!
